on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-slim
    steps:
      - name: checkout the code
        uses: actions/checkout@v6
      
      - name: setup go
        user: actions/setup-go@v6
        with:
          go-version: "1.27.1"

      - name: build
        run: ./scripts/buildprod.sh
